language: ruby
rvm:
  - 2.5.8
env:
  global:
    - CC_TEST_REPORTER_ID=cf3d101c4575090a728a9d8a3a84e99193727f1f447f7ea378156928d055e05d
    - COVERAGE=true
before_script:
  - cp config/database.yml.sample config/database.yml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: "bundle exec rspec"
gemfile:
  - Gemfile
  - Gemfile.next
before_install:
  - gem update bundler

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
